---
# Copyright (C) 2021-2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt

platforms:
  - name: test-cd-ubuntu2004-base
    box: generic/ubuntu2004
    memory: 2048
    cpus: 2
    groups:
      - ubuntu
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.10
  - name: test-cd-ubuntu2204-base
    box: generic/ubuntu2204
    memory: 2048
    cpus: 2
    groups:
      - ubuntu
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.20
  - name: test-cd-arch-base
    box: archlinux/archlinux
    memory: 2048
    cpus: 2
    groups:
      - archlinux
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.30

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint: yamllint . && flake8 && ansible-lint
  inventory:
    host_vars:
      all:
        containerd_tmp_directory: "/opt/tmp/containerd"
        containerd_binary_directory: "/usr/local/sbin"

scenario:
  name: default
  test_sequence:
    - prepare
    - converge

verifier:
  name: ansible
  enabled: true
