---
# Copyright (C) 2021-2026 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt

platforms:
  - name: test-cd-ubuntu2204-base
    box: alvistack/ubuntu-22.04
    memory: 2048
    cpus: 2
    groups:
      - ubuntu
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.20
  - name: test-cd-ubuntu2404-base
    box: alvistack/ubuntu-24.04
    memory: 2048
    cpus: 2
    groups:
      - ubuntu
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.30
  - name: test-cd-ubuntu2404-conf-d
    box: alvistack/ubuntu-24.04
    memory: 2048
    cpus: 2
    groups:
      - ubuntu
      - confd
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.40
  - name: test-cd-arch-base
    box: generic/arch
    memory: 2048
    cpus: 2
    groups:
      - archlinux
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.50

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint: yamllint . && flake8 && ansible-lint
  inventory:
    host_vars:
      all:
        containerd_tmp_directory: "/opt/tmp/containerd"
        containerd_binary_directory: "/usr/local/sbin"
      test-cd-ubuntu2404-conf-d:
        containerd_validate_config: true
        containerd_config_imports:
          - glob: "/etc/containerd/conf.d/*.toml"
            configs:
              10-molecule.toml: |
                # Simple, non-critical override to prove imports work
                plugins."io.containerd.cri.v1.runtime".max_container_log_line_size = 32768

scenario:
  name: default
  test_sequence:
    - prepare
    - converge

verifier:
  name: ansible
  enabled: true
