---
- name: Verify setup
  hosts: all
  vars:
    containerd__nginx_version: "1.24"
  tasks:
    - name: Pull nginx image with ctr
      ansible.builtin.command:
        cmd: "ctr images pull docker.io/library/nginx:{{ containerd__nginx_version }}"
      register: ctr_pull_output
      changed_when: false

    - name: Ensure ctr output contains correct string
      ansible.builtin.assert:
        that:
          - "'done' in ctr_pull_output.stdout"

    - name: Start nginx with ctr
      ansible.builtin.command:
        cmd: "ctr run -d -t docker.io/library/nginx:{{ containerd__nginx_version }} nginx"
      changed_when: false

    - name: List containers
      ansible.builtin.command:
        cmd: "ctr containers ls"
      register: ctr_ls_output
      changed_when: false

    - name: Ensure nginx container running
      ansible.builtin.assert:
        that:
          - "'nginx' in ctr_ls_output.stdout"
